### ISSUE TITLE
Add comma separator

### ISSUE THREAD

**Issue by MrFranke** [epeschier/angular-numeric-directive#1]
Hi! How i can add comma to numeric input?

**Comment by epeschier** [comment]
Hi, the comma or dot separators are read from the $locale like this:
```js
var decimalSeparator = $locale.NUMBER_FORMATS.DECIMAL_SEP;
var groupSeparator = $locale.NUMBER_FORMATS.GROUP_SEP;
```
If you don't want the current locale to be used then these have to be changed. Either hard coded or added as a parameter.

**Comment by epeschier** [comment]
Hi, the comma or dot separators are read from the $locale like this:

``` js
var decimalSeparator = $locale.NUMBER_FORMATS.DECIMAL_SEP;
var groupSeparator = $locale.NUMBER_FORMATS.GROUP_SEP;
```

If you don't want the current locale to be used then these have to be changed. Either hard coded or added as a parameter.
