### ISSUE TITLE
Didn't work with negative value

### ISSUE THREAD

**Issue by hansen168** [epeschier/angular-numeric-directive#17]
Set min value to minus, but the input didn't allow minus sign (-).
I try to type minus sign, but the input show nothing.

Any idea how to fix it?

**Comment by epeschier** [comment]
The min value must be an integer number like "-20". See the example.

**Comment by hansen168** [comment]
Thanks for the reply

Is there any way to make the text red if min value ?
Thanks

**Comment by epeschier** [comment]
Sure, just apply conditional styling with ng-class (yourself).

**Comment by hansen168** [comment]
Thanks
