### ISSUE TITLE
View not formatted when starting on zero

### ISSUE THREAD

**Issue by capesean** [epeschier/angular-numeric-directive#19]
If the starting model value is **0**, then the view renders as **0**. 

Shouldn't it render as **0.00**?

If you tab in and out of the control, without altering the value, the formatting gets applied, and the view is **0.00**

See: https://plnkr.co/edit/SqGtWE2FJ4QCVLSoDFLv?p=preview

**Comment by capesean** [comment]
I believe if you change this line:

https://github.com/epeschier/angular-numeric-directive/blob/89fbb4bf079b1d886a64acca2fe4c5893764dfaf/src/numeric-directive.js#L77

To this:
`                    return (value || value === 0) ? formatPrecision(value) : value;`

it will fix the issue.

**Comment by epeschier** [comment]
Thanks man! Fixed!
