### ISSUE TITLE
package.json fix main src

### ISSUE THREAD

**Issue by cdiaz** [epeschier/angular-numeric-directive#4]
"main": "src/angular-numeric-directive.js",

**Comment by epeschier** [comment]
I don't think this is a valid path?

**Comment by cdiaz** [comment]
if you use this dependence with bower no problem, but if you try to use it browserify, it will not work 

in package.json the main src path is not valid:

"main": "src/angular-numeric-directive.js" <- this file no exist,   the correct path is 

https://github.com/epeschier/angular-numeric-directive/blob/master/src/numeric-directive.js    without "angular" word

**Comment by cdiaz** [comment]
@epeschier ..
